fix: jsx & tsx not converted
extend-chrome/rollup-plugin-chrome-extension pull request #63
Opened 2021-02-16 11:44 UTC by ZakaryCode

When assets is generated, jsx & tsx file path not converted

Community guidelines:

- [x] I have read and understand the
      [contributing guidelines](https://github.com/extend-chrome/.github/blob/master/.github/CONTRIBUTING.md)
      and
      [code of conduct](https://github.com/extend-chrome/.github/blob/master/.github/CODE_OF_CONDUCT.md)

This PR contains:

- [x] bugfix

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)

Breaking Changes?

- [x] no

List any relevant issue numbers:

### Description

There should be a better solution. This solution is based on the current code.

2021-02-16 17:08 UTC, jacksteamdev requested changes
@ZakaryCode Thanks for the PR!

Can you add some tests to make sure that this is working the way we want?

The tests need to check two things:

- `some-file.tsx` is replaced with `some-file.js`
- `some.tsx.js` is not changed

I know `some.tsx.js` is a strange file name, but we want to make sure we don't break things. :wink:

2021-02-19 02:34 UTC, ZakaryCode commented
> @ZakaryCode Thanks for the PR!
> 
> Can you add some tests to make sure that this is working the way we want?
> 
> The tests need to check two things:
> 
> * `some-file.tsx` is replaced with `some-file.js`
> * `some.tsx.js` is not changed
> 
> I know `some.tsx.js` is a strange file name, but we want to make sure we don't break things. 😉

Sorry, I just saw it, but I don't think `some.tsx.js` needs to be fixed. In principle, this is the normal introduction of it.

2021-02-19 02:40 UTC, ZakaryCode commented
FYI, that we writed `web_accessible_resources` that it was incorrect.

```json
  // script not import
  "web_accessible_resources": [
    "./src/content.js",
  ],
  // script import
  "web_accessible_resources": [
    "src/content.js",
  ],

```

Sorry, I didn't open a new issue to explain this, but although these two issues are not the same problem, they both lead to `content_scripts` are not working properly.

2021-03-01 18:37 UTC, closed without merging

2021-03-01 20:30 UTC, jacksteamdev commented
@ZakaryCode I wrote tests for this feature and put you as co-author for #67

Thanks for contributing!